name: Build Firmware Artifacts

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # keyboard folder name to compile path keyboards\<keyboard>
        # it's not recommended to build multiple keyboards at the same time since they will need the same hardware and keymap definitions.
        keyboard: ['crkbd']
        # config folder name to compile in path keyboards\<keyboard>\config\<config>
        # you can compile multiple configurations for a single keyboard
        config: ['single','left','right']
        # fqbn from the community_nrf52 BSP.
        # current options:
        # 'pca10056', 'pca10059', 'feather52832'
        # note that you won't be able to upload the firmware to a nrf52832 board using uf2. 
        # uf2 files can only be uploaded to the nrf52840 boards.
        # fqbn folder name to compile in path keyboards\<keyboard>\hardware\<fqbn>\<config>
        fqbn: ['pca10056']
        # hardware folder name to compile in path keyboards\<keyboard>\hardware\<fqbn>\<config>
        hardware: ['bluemicro840']
        # keymap folder name to compile in path keyboards\<keyboard>\keymaps\<keymap>
        # you can compile multiple keymaps for a single keyboard
        keymap: ['default']

    runs-on: ubuntu-latest
    
    steps:    
      # First of all, we clone the repo using the checkout action.
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      # We use the arduino/setup-arduino-cli action to install and
      # configure the Arduino CLI on the system.
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1
        
      - name: Install BSP and Libraries
        env:
          BSP_URL: https://github.com/jpconstantineau/Community_nRF52_Arduino/releases/latest/download/package_jpconstantineau_boards_index.json
          BSP_PATH: .arduino15/packages/community_nrf52/hardware/nrf52
          BSP_URL_ADA: https://adafruit.github.io/arduino-board-index/package_adafruit_index.json
          BSP_PATH_ADA: .arduino15/packages/adafruit/hardware/nrf52
        run: |
          pip3 install adafruit-nrfutil
          arduino-cli config init
          arduino-cli core update-index
          arduino-cli core update-index --additional-urls $BSP_URL_ADA
          arduino-cli core install adafruit:nrf52 --additional-urls $BSP_URL_ADA
          arduino-cli core update-index --additional-urls $BSP_URL
          arduino-cli core install community_nrf52:nrf52 --additional-urls $BSP_URL
          arduino-cli core list
          arduino-cli board listall
          # Install library dependencies
          arduino-cli lib install   "Adafruit GFX Library"  "Adafruit NeoPixel"  "Adafruit SSD1306" 
          arduino-cli lib list

      - name: Copy keyboard config files to firmware folder
        run: |
          cp -f firmware/keyboards/${{ matrix.keyboard }}/config/${{ matrix.config }}/keyboard_config.h  firmware/keyboard_config.h
          cp -f firmware/keyboards/${{ matrix.keyboard }}/hardware/${{ matrix.fqbn }}/${{ matrix.hardware }}/hardware_config.h firmware/hardware_config.h
          cp -f firmware/keyboards/${{ matrix.keyboard }}/keymaps/${{ matrix.keymap }}/keymap.h firmware/keymap.h
          cp -f firmware/keyboards/${{ matrix.keyboard }}/keymaps/${{ matrix.keymap }}/keymap.cpp firmware/keymap.cpp

      - name: Compile Sketch
        env:
          BSP_PATH: .arduino15/packages/adafruit/hardware/nrf52
        run: |
          arduino-cli compile --fqbn community_nrf52:nrf52:${{ matrix.fqbn }}  ./firmware
          BSP_VERSION=`eval ls $HOME/$BSP_PATH`
          BUILDLOC=`eval ls ./firmware/build`
          python $HOME/$BSP_PATH/$BSP_VERSION/tools/uf2conv/uf2conv.py ./firmware/build/$BUILDLOC/firmware.ino.hex -c -f 0xADA52840 -o ./firmware/build/$BUILDLOC/firmware.ino.uf2
          ls -lR ./firmware/build/$BUILDLOC/
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.keyboard }}-${{ matrix.hardware }}-${{ matrix.config }}-${{ matrix.keymap }}
          path: |
            firmware/build